version: '3.8'

services:

  bangkok-earthquake-notify:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bangkok-earthquake-notify
    env_file:
      - .env
    restart: always
    depends_on:
      - earthquake-redis
    networks:
      - nw-bangkok-earthquake-notify

  earthquake-redis:
    image: redis:7
    container_name: earthquake-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - nw-bangkok-earthquake-notify

volumes:
  redis-data:

networks:
  nw-bangkok-earthquake-notify:
    driver: bridge