version: '3.8'

services:

  bangkok-earthquake-notify:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bangkok-earthquake-notify
    env_file:
      - .env
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: earthquake-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
